weights: ''
cfg: ../yolov5/models/yolov5s.yaml
data: data.yaml
hyp: ../yolov5/data/hyps/hyp.scratch.yaml
epochs: 2
batch_size: 32
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: yolov5s_results
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs\train\yolov5s_results2
